version: "3.2"
services:
  app:
    build: ./infra/php
    container_name: php
    volumes:
      - type: bind
        source: ./infra/php/php.ini
        target: /usr/local/etc/php/php.ini
      - type: bind
        source: ./backend/public
        target: /usr/share/nginx/html
    depends_on:
      - db
    working_dir: /usr/share/nginx/html

  web:
    image: nginx:1.20.1-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./infra/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./backend/public
        target: /usr/share/nginx/html
    depends_on:
      - app
    working_dir: /usr/share/nginx/html

  db:
    build: ./infra/mysql
    container_name: mysql
    # environment:
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # MYSQL_DATABASE: ${MYSQL_DATABASE}
      # TZ: ${TZ}
    volumes:
      - sql-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      # PMA_HOST: ${PMA_HOST}
      # PMA_USER: ${PMA_USER}
      # PMA_PASSWORD: ${PMA_PASSWORD}
      PMA_HOST: mysql
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_pass
    ports:
      - 3000:80
    volumes:
      - phpmyadmin-volume:/sessions
    depends_on:
      - db

volumes:
  sql-volume:
  phpmyadmin-volume: